version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "5173:5173"  # Vite dev server port
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: respace
      DB_USERNAME: postgres
      DB_PASSWORD: gishan
      POSTGRES_HOST_AUTH_METHOD: trust
      VITE_APP_URL: "http://localhost:8000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - respace-network

  postgres:
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: respace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gishan
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - respace-network

volumes:
  postgres_data:

networks:
  respace-network:
    driver: bridge