version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map Laravel server to host
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: respace
      DB_USERNAME: postgres
      DB_PASSWORD: gishan
    depends_on:
      - postgres
    volumes:
      - .:/var/www/html

  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: respace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gishan
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
