services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: respace
      DB_USERNAME: postgres
      DB_PASSWORD: gishan
      POSTGRES_HOST_AUTH_METHOD: trust
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - respace-network

  postgres:
    image: postgres:15-bullseye
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: respace
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gishan
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - respace-network

volumes:
  postgres_data:

networks:
  respace-network:
    driver: bridge